### ISSUE TITLE
Sign in: Continue with Google

### ISSUE THREAD

**Issue by elstevega** [hammem/monarchmoney#10]
I use 'Continue with Google' to sign-in - any thoughts on how to accommodate this?

**Comment by hammem** [comment]
Good question!  I'll dig into this and see what is needed to automate the login flow.

**Comment by hammem** [comment]
Added an answer to this question in the readme via commit [2ac5b93](https://github.com/hammem/monarchmoney/commit/2ac5b930ccc57733d401b88306da6d01463ea8d9).
