### ISSUE TITLE
add Account ID to the get_transactions() function

### ISSUE THREAD

**Issue by dsteiner10** [hammem/monarchmoney#14]
Would it be possible to add an account ID/name to the get_transactions() function? I have tried to play around with it myself and haven't found a way to do it, but I have never worked with gql, so I'm hoping your expertise can resolve it.

If adding a new field isn't an option, would pulling transactions for specific account IDs be an option?

**Comment by hammem** [comment]
@dsteiner10, this should be working now!  If you're using this library via pip, `pip install --upgrade monarchmoney` should get you the latest.

**Comment by dsteiner10** [comment]
@hammem Thank you for such a fast response!
