### ISSUE TITLE
[Feature] Add method to trigger account refresh

### ISSUE THREAD

**Issue by CalvinChanCan** [hammem/monarchmoney#43]

**Comment by hammem** [comment]
This all looks good!  If you want to put up a PR, @CalvinChanCan , go for it.  If not, I can put it together.  Recommend including a `force_account_refresh_and_wait()` convenience method that calls both.  Generators can be tricky for newer developers and don't want to confuse folks or need to force them to ask a question here.

**Comment by hammem** [comment]
@lzilioli / @CalvinChanCan - please see if #49 does what you're looking for here.
