### ISSUE TITLE
Frequent 404s with MFA login

### ISSUE THREAD

**Issue by guillochon** [hammem/monarchmoney#45]
I'm not sure what Monarch's API rate limits are, but I'm getting frequent 404's on login:

```
Traceback (most recent call last):
  File "/var/lib/homebridge/monarch.py", line 26, in <module>
    asyncio.run(main(), debug=True)
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/var/lib/homebridge/monarch.py", line 14, in main
    await mm.login(
  File "/home/pi/.local/lib/python3.9/site-packages/monarchmoney/monarchmoney.py", line 108, in login
    await self._login_user(email, password, mfa_secret_key)
  File "/home/pi/.local/lib/python3.9/site-packages/monarchmoney/monarchmoney.py", line 768, in _login_user
    raise LoginFailedException(
monarchmoney.monarchmoney.LoginFailedException: HTTP Code 404: Not Found
```

I'm speculating that this is hitting some sort of rate limit, but I am not sure if that's actually what's happening. Regardless, handling this more gracefully would be nice, or at least documenting the default API rate limits.

Code I used:
```
import asyncio

from monarchmoney import MonarchMoney

with open("monarch-creds.json", "r") as f:
    creds = json.load(f)

async def main():
    mm = MonarchMoney()

    await mm.login(
        email=creds["email"],
        password=creds["password"],
        save_session=False,
        use_saved_session=False,
        mfa_secret_key=creds["mfa_secret_key"],
    )

asyncio.run(main(), debug=True)
```

**Comment by hammem** [comment]
Thanks, @guillochon !  If you have a sense of what the rate limits might be, we can update the docs.  I, personally, haven't encountered this.

And, if there's a specific type of transaction or data set you're trying to get and can share, there might be a more efficient way to retrieve it, which we can add to the API.

**Comment by guillochon** [comment]
I've found that just the login code above is enough to get the 404s, if I run it frequently enough (roughly a few times in a minute). If someone else could try and reproduce on their end maybe we can figure out exactly what the login limit is.

**Comment by hammem** [comment]
Ah, ok, that makes sense.

You shouldn’t need to keep calling login.  Once in a session should do it.

If you are calling this programmatically, recommend using save_session() to
persist the token details. Provided the pickle file is where the class
expects it, subsequent calls to login() won’t actually hit the API and you
can go straight to other API calls to fetch data.

I use an approach like this in an AWS Lambda and it works without issue.

**Comment by guillochon** [comment]
How long do the tokens typically last before they need to be re-acquired?

**Comment by hammem** [comment]
They seem to be good for a really long time.  I've had them last for months, but I haven't looked to see if a precise time span can be determined.

**Comment by guillochon** [comment]
OK great, I think the session stuff is undocumented so it'd prolly be a good idea to add that to the readme at some point, but I'm going to close this since it's not urgent.
