### ISSUE TITLE
Add unit test coverage

### ISSUE THREAD

**Issue by hammem** [hammem/monarchmoney#48]
As this library grows and matures, it's going to need unit (and likely integration) tests.  Otherwise, I'm sure I'll release a version to PyPI that breaks things for everyone!

I'm flexible on testing regimes we use.  Resolving this issue should include tests for:

* setting up a connection
* getting accounts
* searching transactions

Also, setup a workflow to run the tests when folks put up a PR or create a release.

**Comment by Rachit1313** [comment]
I would like to work on this one

**Comment by hammem** [comment]
Amazing!  Go for it!

**Comment by hammem** [comment]
Added initial support for unit tests in bbd68f59be03ec4127993643cfd09a8052cec51b
