### ISSUE TITLE
Add methods to manipulate the Categories

### ISSUE THREAD

**Issue by azinsharaf** [hammem/monarchmoney#61]
Does this api have methods to list the Categories and delete some of them? I've imported my Mint data into Monarch and ended up with 3000 custom categories in "Other" group. Their support isn't helpful to clean it up.

**Comment by hammem** [comment]
@azinsharaf , thanks for raising this issue!  Happy to add methods for listing categories and deleting them!

**Comment by hammem** [comment]
just to be clear, @azinsharaf , the existing methods `get_transaction_categories()` and `get_transaction_category_groups()` will let you retrieve the existing ones, we just need to add a methods to edit and delete them.

**Comment by grablair** [comment]
Just merged @hammem's changes. Should be out in the next version

**Comment by azinsharaf** [comment]
thanks for writing it so quickly. 
i am trying to learn how to use this library. i might ask my questions in the discussion section. thanks again!

**Comment by hammem** [comment]
No worries, @azinsharaf !  I appreciate the time you took to ask for it.
