### ISSUE TITLE
publish this to pypi?

### ISSUE THREAD

**Issue by sanghviharshit** [hammem/monarchmoney#8]
Thanks for creating this library. I just finished creating a custom component for Home Assistant using this library. Would you be interested in publishing this as a package on pypi.org, so I can use it as a dependency?

You can find my custom component here - https://github.com/sanghviharshit/ha-monarchmoney

**Comment by hammem** [comment]
Yeah, sure, will do!

**Comment by hammem** [comment]
@sanghviharshit , PR#9 is up, mind taking a look?
