### ISSUE TITLE
Add delete_session to delete saved session info

### ISSUE THREAD

**Issue by Unusual-Ad** [hammem/monarchmoney#88]
For security purposes, should add a delete_session function to the class MonarchMoney to enabling deleting the saved session file.

I'm new to Python/Git, but I think this is probably really straightforward:
    def delete_session_file(self,filename: str = SESSION_FILE) -> None:
        """
        Deletes Python pickle file of saved session info if it exists.
        """
        if os.path.isfile(filename):
            os.remove(filename)

**Comment by hammem** [comment]
This has been added and will go to PyPI on the next release.
