### ISSUE TITLE
Login function doesn't properly return an exception when no email or password is provided

### ISSUE THREAD

**Issue by Unusual-Ad** [hammem/monarchmoney#90]
When using interactiveLogin, if no email or password is provided an exception doesn't get raised by login. This like like it's due to the fact that input() is used to retrieve those values and entering nothing results in the variable being an empty string (i.e. '') instead of None. 

In login():
...
if email is None or password is None:
            raise LoginFailedException(
                "Email and password are required to login when not using a saved session."
            )

looks like this can be fixed by updating to check the variables being == '' instead of None, but not sure if there's something else going wrong prior to that

**Comment by hammem** [comment]
This is fixed and will go to PyPI on the next release.
