### ISSUE TITLE
Recent change to API causing error when calling get_transactions

### ISSUE THREAD

**Issue by CalvinChanCan** [hammem/monarchmoney#95]
Recently, after an API change, I've been getting an error when calling `get_transactions`. Can anyone else confirm if they're getting errors as well? After testing around with it, I've found that removing the account in the graphql query fixed the error but meaning the account is no longer in the response.

https://github.com/hammem/monarchmoney/blob/main/monarchmoney/monarchmoney.py#L1239

Stacktrace:
```
Traceback (most recent call last):
  File "C:\Users\cchan\PycharmProjects\monarchmoney\monarchmoney\monarchmoney.py", line 1321, in get_transactions
    return await self.gql_call(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cchan\PycharmProjects\monarchmoney\monarchmoney\monarchmoney.py", line 2634, in gql_call
    return await self._get_graphql_client().execute_async(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cchan\PycharmProjects\monarchmoney\.venv\Lib\site-packages\gql\client.py", line 285, in execute_async
    return await session.execute(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cchan\PycharmProjects\monarchmoney\.venv\Lib\site-packages\gql\client.py", line 1231, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': "Something went wrong while processing: ['allTransactions', 'results', 4] on request_id: 107af4308b774b779d356d241c6d37ca.", 'locations': [{'line': 4, 'column': 5}], 'path': ['allTransactions', 'results', 4]}
```

**Comment by quinn-p-mchugh** [comment]
Hi @CalvinChanCan,

Just encountered this issue as well. I'm trying to export all my ~6000 transactions to JSON via `mm.get_transactions(limit=10000000000000000000)`.

I'm initializing `MonarchMoney` and exporting the transactions like so:
```
mm = MonarchMoney(timeout=20)
await mm.login(environ["EMAIL"], environ["PASSWORD"])
mm.get_transactions(limit=10000000000000000000)
```

**Comment by grablair** [comment]
Query now submitted when loading transactions via the web UI (using dev tools to listen):

```
query Web_GetTransactionsList($offset: Int, $limit: Int, $filters: TransactionFilterInput, $orderBy: TransactionOrdering) {
  allTransactions(filters: $filters) {
    totalCount
    results(offset: $offset, limit: $limit, orderBy: $orderBy) {
      id
      ...TransactionOverviewFields
      __typename
    }
    __typename
  }
  transactionRules {
    id
    __typename
  }
}

fragment TransactionOverviewFields on Transaction {
  id
  amount
  pending
  date
  hideFromReports
  plaidName
  notes
  isRecurring
  reviewStatus
  needsReview
  dataProviderDescription
  attachments {
    id
    __typename
  }
  isSplitTransaction
  category {
    id
    name
    icon
    group {
      id
      type
      __typename
    }
    __typename
  }
  merchant {
    name
    id
    transactionsCount
    __typename
  }
  tags {
    id
    name
    color
    order
    __typename
  }
  __typename
}
```

The web UI isn't really using the account on the transactions search page, so I suppose it makes sense for them to remove it in order to reduce payload size...

FWIW, I am _not_ seeing this when I simply run:

```
asyncio.run(mm.get_transactions())
```

My transactions return successfully.

**Comment by grablair** [comment]
@CalvinChanCan what exact command are you running?

**Comment by quinn-p-mchugh** [comment]
@grablair 
I believe this has to do with the size of the payload. 

On my end, using `await mm.get_transactions()` does not produce the error, whereas using `await mm.get_transactions(limit=10000000)` does.

**Comment by CalvinChanCan** [comment]
@grablair, the API is using GraphQL, which allows the client to requests only the fields it needs in a single call, so the account should be available despite not being in the Web UI's request. Its currently working again for me when running `await mm.get_transactions()` where the account is in the response again but unsure if that was fixed. 

There seem to be plans to bring the account into the transactions page eventually according to this [post] so the account would eventually be added to the GraphQL's request.

(https://www.reddit.com/r/MonarchMoney/comments/1azrhpm/comment/ks9yglv/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

@quinn-p-mchugh , there might be a separate error when trying to retrieve transactions over the 1000 limit. It may be better to use an offset though you may need asyncio.

```
      transaction_response = asyncio.run(self.client.get_transactions())

      transactions = []

      total_count = transaction_response.get("allTransactions").get("totalCount")
      for offset in range(0, total_count, 1000):
          transaction_response = asyncio.run(self.client.get_transactions(
              offset=offset,
              limit=1000,
          ))
          transactions_results = transaction_response.get("allTransactions").get(
              "results"
          )
          transactions.extend(transactions_results)

```

**Comment by quinn-p-mchugh** [comment]
Hi @CalvinChanCan ,

Ah, didn't realize there was an offset parameter.

Thanks for the example code. I'll give that a try!
